name: Snyk Catch
run-name: Run Snyk Checks
on:
  status:
  check_run:

jobs:
  run-status-checks:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup nodejs
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - name: Run Checks
          run: |
            npm i -g yarn
            yarn global add @vercel/ncc
            yarn install
            yarn build
            node dist/index.js